"""ADR-11 baseline: consolidated adaptive + betb2b schema

Revision ID: c7ea08fedb55
Revises: 
Create Date: 2026-07-25 16:54:30.800989
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c7ea08fedb55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('approval_count', sa.Integer(), nullable=False),
    sa.Column('total_boost', sa.Float(), nullable=False),
    sa.Column('related_boost', sa.Float(), nullable=False),
    sa.Column('first_approval', sa.DateTime(), nullable=True),
    sa.Column('last_approval', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_weights_strategy_type'), ['strategy_type'], unique=False)
        batch_op.create_index('ix_approval_weights_strategy_unique', ['strategy_type'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_id', sa.Integer(), nullable=True),
    sa.Column('selector_id', sa.String(length=100), nullable=True),
    sa.Column('selector', sa.Text(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('confidence_at_time', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('suggested_alternative', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_failure_id'), ['failure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_selector_id'), ['selector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('bulk_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('total_time_ms', sa.Float(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count_op', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_operations_operation_id'), ['operation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_bulk_operations_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_operations_user_id'), ['user_id'], unique=False)

    op.create_table('failure_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('selector_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('recipe_id', sa.String(length=255), nullable=True),
    sa.Column('sport', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=1000), nullable=True),
    sa.Column('strategy_used', sa.String(length=100), nullable=True),
    sa.Column('previous_strategy_used', sa.String(length=100), nullable=True),
    sa.Column('confidence_score_at_failure', sa.Float(), nullable=True),
    sa.Column('tab_type', sa.String(length=50), nullable=True),
    sa.Column('page_state', sa.JSON(), nullable=True),
    sa.Column('resolution_time', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_note', sa.String(length=1000), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failure_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_failure_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_events_error_type'), ['error_type'], unique=False)
        batch_op.create_index('ix_failure_events_error_type_timestamp', ['error_type', 'timestamp'], unique=False)
        batch_op.create_index('ix_failure_events_flagged', ['flagged'], unique=False)
        batch_op.create_index('ix_failure_events_flagged_at', ['flagged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_events_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index('ix_failure_events_recipe_timestamp', ['recipe_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_events_selector_id'), ['selector_id'], unique=False)
        batch_op.create_index('ix_failure_events_selector_timestamp', ['selector_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_events_severity'), ['severity'], unique=False)
        batch_op.create_index('ix_failure_events_severity_timestamp', ['severity', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_events_site'), ['site'], unique=False)
        batch_op.create_index('ix_failure_events_site_timestamp', ['site', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_events_sport'), ['sport'], unique=False)
        batch_op.create_index('ix_failure_events_sport_site', ['sport', 'site'], unique=False)
        batch_op.create_index('ix_failure_events_sport_timestamp', ['sport', 'timestamp'], unique=False)
        batch_op.create_index('ix_failure_events_timestamp_desc', ['timestamp'], unique=False)

    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sport', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'site', name='uq_feature_flag_sport_site')
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_site'), ['site'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_flags_sport'), ['sport'], unique=False)

    op.create_table('generation_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.String(length=255), nullable=False),
    sa.Column('current_generation', sa.Integer(), nullable=False),
    sa.Column('generations_survived', sa.Integer(), nullable=False),
    sa.Column('generation_failures', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('first_generation', sa.DateTime(), nullable=True),
    sa.Column('last_generation_change', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_data_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index('ix_generation_data_recipe_unique', ['recipe_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_generation_data_site'), ['site'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_data_sport'), ['sport'], unique=False)

    op.create_table('performance_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_performance_cache_expires_at'), ['expires_at'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('selectors', sa.JSON(), nullable=False),
    sa.Column('parent_recipe_id', sa.String(length=255), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('generations_survived', sa.Integer(), nullable=True),
    sa.Column('last_successful_resolution', sa.DateTime(), nullable=True),
    sa.Column('last_failure_timestamp', sa.DateTime(), nullable=True),
    sa.Column('failure_severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'version', name='uq_recipe_version')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('rejection_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.Column('total_penalty', sa.Float(), nullable=False),
    sa.Column('related_penalty', sa.Float(), nullable=False),
    sa.Column('first_rejection', sa.DateTime(), nullable=True),
    sa.Column('last_rejection', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rejection_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rejection_weights_strategy_type'), ['strategy_type'], unique=False)
        batch_op.create_index('ix_rejection_weights_strategy_unique', ['strategy_type'], unique=True)

    op.create_table('selector_approval_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('selector_string', sa.String(length=1000), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_at_approval', sa.Float(), nullable=True),
    sa.Column('boosted_confidence', sa.Float(), nullable=True),
    sa.Column('failure_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approval_notes', sa.String(length=1000), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('selector_approval_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selector_approval_history_failure_id'), ['failure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selector_approval_history_selector_string'), ['selector_string'], unique=False)
        batch_op.create_index(batch_op.f('ix_selector_approval_history_site'), ['site'], unique=False)
        batch_op.create_index(batch_op.f('ix_selector_approval_history_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_selector_approval_history_strategy_type'), ['strategy_type'], unique=False)

    op.create_table('selector_rejection_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('selector_string', sa.String(length=1000), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_at_rejection', sa.Float(), nullable=True),
    sa.Column('penalized_confidence', sa.Float(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('reason_pattern', sa.String(length=50), nullable=True),
    sa.Column('failure_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('rejected_by', sa.String(length=255), nullable=True),
    sa.Column('rejection_notes', sa.String(length=1000), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('selector_rejection_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selector_rejection_history_failure_id'), ['failure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selector_rejection_history_selector_string'), ['selector_string'], unique=False)
        batch_op.create_index(batch_op.f('ix_selector_rejection_history_site'), ['site'], unique=False)
        batch_op.create_index(batch_op.f('ix_selector_rejection_history_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_selector_rejection_history_strategy_type'), ['strategy_type'], unique=False)

    op.create_table('triage_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('failure_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('load_time_ms', sa.Float(), nullable=True),
    sa.Column('action_time_ms', sa.Float(), nullable=True),
    sa.Column('total_time_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triage_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triage_metrics_failure_id'), ['failure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_metrics_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('default_view', sa.String(length=20), nullable=False),
    sa.Column('custom_settings', sa.JSON(), nullable=True),
    sa.Column('last_view_mode', sa.String(length=20), nullable=True),
    sa.Column('view_mode_switches', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_api_key_hash'), ['api_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('view_usage_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('view_mode', sa.String(length=20), nullable=False),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('session_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('view_usage_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_view_usage_analytics_user_id'), ['user_id'], unique=False)

    op.create_table('countries',
    sa.Column('country_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('markets',
    sa.Column('market_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('market_type', sa.Text(), nullable=True),
    sa.Column('raw_g', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.create_table('scrape_runs',
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('skin', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('sport', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('template_version', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sport_id')
    )
    op.create_table('leagues',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('backend_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('backend_id'),
    sa.UniqueConstraint('name', 'sport_id', name='uq_teams_name_sport')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('home_team_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('away_team_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('home_name', sa.Text(), nullable=True),
    sa.Column('away_name', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_league', ['league_id'], unique=False)
        batch_op.create_index('ix_events_sport', ['sport_id'], unique=False)
        batch_op.create_index('ix_events_start_time', ['start_time'], unique=False)

    op.create_table('event_states',
    sa.Column('state_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('skin', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('period', sa.Text(), nullable=True),
    sa.Column('time_remaining', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.run_id'], ),
    sa.PrimaryKeyConstraint('state_id')
    )
    with op.batch_alter_table('event_states', schema=None) as batch_op:
        batch_op.create_index('ix_states_event', ['event_id', 'captured_at'], unique=False)

    op.create_table('h2h_games',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('skin', sa.Text(), nullable=False),
    sa.Column('game_id', sa.Text(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('team1_backend_id', sa.Text(), nullable=True),
    sa.Column('team2_backend_id', sa.Text(), nullable=True),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('sub_score1', sa.Integer(), nullable=True),
    sa.Column('sub_score2', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('h2h_games', schema=None) as batch_op:
        batch_op.create_index('ix_h2h_event', ['event_id'], unique=False)

    op.create_table('odds_snapshots',
    sa.Column('snap_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('skin', sa.Text(), nullable=False),
    sa.Column('market_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('selection_name', sa.Text(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('raw_t', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.market_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.run_id'], ),
    sa.PrimaryKeyConstraint('snap_id')
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_odds_event', ['event_id', 'skin', 'captured_at'], unique=False)
        batch_op.create_index('ix_odds_event_extracted', ['event_id', 'captured_at'], unique=False)
        batch_op.create_index('ix_odds_market', ['event_id', 'skin', 'market_id', 'selection_name', 'captured_at'], unique=False)

    op.create_table('period_scores',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('skin', sa.Text(), nullable=False),
    sa.Column('period_key', sa.Integer(), nullable=True),
    sa.Column('period_name', sa.Text(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('period_scores', schema=None) as batch_op:
        batch_op.create_index('ix_periods_event', ['event_id', 'captured_at'], unique=False)

    op.create_table('statistics',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('skin', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('h2h_period_scores',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('h2h_game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=True),
    sa.Column('period_key', sa.Integer(), nullable=True),
    sa.Column('period_name', sa.Text(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['h2h_game_id'], ['h2h_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('h2h_period_scores')
    op.drop_table('statistics')
    with op.batch_alter_table('period_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_periods_event')

    op.drop_table('period_scores')
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_odds_market')
        batch_op.drop_index('ix_odds_event_extracted')
        batch_op.drop_index('ix_odds_event')

    op.drop_table('odds_snapshots')
    with op.batch_alter_table('h2h_games', schema=None) as batch_op:
        batch_op.drop_index('ix_h2h_event')

    op.drop_table('h2h_games')
    with op.batch_alter_table('event_states', schema=None) as batch_op:
        batch_op.drop_index('ix_states_event')

    op.drop_table('event_states')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_start_time')
        batch_op.drop_index('ix_events_sport')
        batch_op.drop_index('ix_events_league')

    op.drop_table('events')
    op.drop_table('teams')
    op.drop_table('leagues')
    op.drop_table('sports')
    op.drop_table('scrape_runs')
    op.drop_table('markets')
    op.drop_table('countries')
    with op.batch_alter_table('view_usage_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_view_usage_analytics_user_id'))

    op.drop_table('view_usage_analytics')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_api_key_hash'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('triage_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triage_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_triage_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_triage_metrics_failure_id'))

    op.drop_table('triage_metrics')
    with op.batch_alter_table('selector_rejection_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selector_rejection_history_strategy_type'))
        batch_op.drop_index(batch_op.f('ix_selector_rejection_history_sport'))
        batch_op.drop_index(batch_op.f('ix_selector_rejection_history_site'))
        batch_op.drop_index(batch_op.f('ix_selector_rejection_history_selector_string'))
        batch_op.drop_index(batch_op.f('ix_selector_rejection_history_failure_id'))

    op.drop_table('selector_rejection_history')
    with op.batch_alter_table('selector_approval_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selector_approval_history_strategy_type'))
        batch_op.drop_index(batch_op.f('ix_selector_approval_history_sport'))
        batch_op.drop_index(batch_op.f('ix_selector_approval_history_site'))
        batch_op.drop_index(batch_op.f('ix_selector_approval_history_selector_string'))
        batch_op.drop_index(batch_op.f('ix_selector_approval_history_failure_id'))

    op.drop_table('selector_approval_history')
    with op.batch_alter_table('rejection_weights', schema=None) as batch_op:
        batch_op.drop_index('ix_rejection_weights_strategy_unique')
        batch_op.drop_index(batch_op.f('ix_rejection_weights_strategy_type'))

    op.drop_table('rejection_weights')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_recipe_id'))

    op.drop_table('recipes')
    with op.batch_alter_table('performance_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_performance_cache_cache_key'))

    op.drop_table('performance_cache')
    with op.batch_alter_table('generation_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_data_sport'))
        batch_op.drop_index(batch_op.f('ix_generation_data_site'))
        batch_op.drop_index('ix_generation_data_recipe_unique')
        batch_op.drop_index(batch_op.f('ix_generation_data_recipe_id'))

    op.drop_table('generation_data')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_sport'))
        batch_op.drop_index(batch_op.f('ix_feature_flags_site'))

    op.drop_table('feature_flags')
    with op.batch_alter_table('failure_events', schema=None) as batch_op:
        batch_op.drop_index('ix_failure_events_timestamp_desc')
        batch_op.drop_index('ix_failure_events_sport_timestamp')
        batch_op.drop_index('ix_failure_events_sport_site')
        batch_op.drop_index(batch_op.f('ix_failure_events_sport'))
        batch_op.drop_index('ix_failure_events_site_timestamp')
        batch_op.drop_index(batch_op.f('ix_failure_events_site'))
        batch_op.drop_index('ix_failure_events_severity_timestamp')
        batch_op.drop_index(batch_op.f('ix_failure_events_severity'))
        batch_op.drop_index('ix_failure_events_selector_timestamp')
        batch_op.drop_index(batch_op.f('ix_failure_events_selector_id'))
        batch_op.drop_index('ix_failure_events_recipe_timestamp')
        batch_op.drop_index(batch_op.f('ix_failure_events_recipe_id'))
        batch_op.drop_index('ix_failure_events_flagged_at')
        batch_op.drop_index('ix_failure_events_flagged')
        batch_op.drop_index('ix_failure_events_error_type_timestamp')
        batch_op.drop_index(batch_op.f('ix_failure_events_error_type'))
        batch_op.drop_index(batch_op.f('ix_failure_events_correlation_id'))

    op.drop_table('failure_events')
    with op.batch_alter_table('bulk_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_operations_user_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_operations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_bulk_operations_operation_id'))

    op.drop_table('bulk_operations')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_selector_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_failure_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action_type'))

    op.drop_table('audit_log')
    with op.batch_alter_table('approval_weights', schema=None) as batch_op:
        batch_op.drop_index('ix_approval_weights_strategy_unique')
        batch_op.drop_index(batch_op.f('ix_approval_weights_strategy_type'))

    op.drop_table('approval_weights')
    # ### end Alembic commands ###
